# Generated by Django 4.1.6 on 2023-02-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='numero',
        ),
    ]
